In [23]:
import numpy as np
import pandas as pd

In [24]:
df =pd.read_csv('customer.csv')

In [25]:
df.sample(5)

age  gender   review education purchased
29   83  Female  Average        UG       Yes
48   39  Female     Good        UG       Yes
24   16  Female  Average        PG       Yes
16   59    Male     Poor        UG       Yes
6    18    Male     Good    School        No

In [26]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [27]:
df =df.iloc[:,2:]

In [28]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [29]:
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train ,y_test =train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [30]:
X_train

review education
5   Average    School
15     Poor        UG
48     Good        UG
34  Average    School
19     Poor        PG
49     Good        UG
25     Good    School
43     Poor        PG
8   Average        UG
40     Good    School
33     Good        PG
42     Good        PG
11     Good        UG
28     Poor    School
2      Good        PG
46     Poor        PG
26     Poor        PG
41     Good        PG
31     Poor    School
17     Poor        UG
1      Poor        UG
13  Average    School
24  Average        PG
7      Poor    School
38     Good    School
47     Good        PG
12     Poor    School
22     Poor        PG
39     Poor        PG
4   Average        UG
44  Average        UG
20  Average    School
6      Good    School
23     Good    School
16     Poor        UG
14     Poor        PG
35     Poor    School
0   Average    School
21  Average        PG
36     Good        UG

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
oe = OrdinalEncoder(categories =[['Poor','Average','Good'],['School','UG','PG']])

In [33]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [34]:
X_train =oe.transform(X_train)

In [35]:
X_train

array([[1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [1., 2.],
       [2., 1.]])

# LabelEncoding
only for encoding target categorical variable

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le =LabelEncoder()

In [38]:
le.fit(y_train)

LabelEncoder()

In [39]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [40]:
y_train =le.transform(y_train)
y_test = le.transform(y_test)

In [41]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1])

In [42]:
y_test

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])